<a href="https://colab.research.google.com/github/surekhavydyula4-cmd/Numpy./blob/main/Numpy_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#min()
import numpy as np
a=np.array([4,6,3,2])
print(a.min())


2


In [4]:
#max()
import numpy as np
a=np.array([4,6,3,2])
print(a.max())

6


In [5]:
#sum()
import numpy as np
a=np.array([4,6,3,2])
print(a.sum())

15


In [6]:
#mean()
import numpy as np
a=np.array([4,6,3,2])
print(a.mean())

3.75


In [8]:
#std
import numpy as np
a=np.array([4,6,3,2])
print(a.std())

1.479019945774904


In [ ]:
# reshape()
import numpy as np
a=[[1,2,3],[4,5,6]]
arr=np.array(a)
print(arr.reshape(3,2))
print(arr.reshape(1,2)) #error

In [ ]:
# transpose()
import numpy as np
a=[[1,2,3],[4,5,6]]
ar=np.array(a)
print(ar.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [9]:
#flatten()
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.flatten())

[1 2 3 4 5 6]


In [28]:
#sort()
import numpy as np
a = np.array([[55, 13, 12], [99, 2, 1]])
b = np.array(a)
print(b)
b.sort()
print(b)


[[55 13 12]
 [99  2  1]]
[[12 13 55]
 [ 1  2 99]]


In [33]:
# diagonal
import numpy as np
a=np.array([[2,3],[2,6]])
print(a.diagonal())

[2 6]


In [34]:
# trace
import numpy as np
a=np.array([[2,3],[2,6]])
print(a.trace())

8


In [35]:
#addition of two arrays
import numpy as np
a=np.array([[3,2,1],[2,1,4]])
b=np.array([[5,10,4],[10,25,2]])
print(np.add(a,b))

[[ 8 12  5]
 [12 26  6]]


In [36]:
#subtraction of two arrays
import numpy as np
a=np.array([[3,2,1],[2,1,4]])
b=np.array([[5,10,4],[10,25,2]])
print(np.subtract(a,b))

[[ -2  -8  -3]
 [ -8 -24   2]]


In [39]:
#multipliaction of two arrays
import numpy as np
a=np.array([[3,2,1],[2,1,4]])
b=np.array([[5,10,4],[10,25,2]])
print(np.multiply(a,b))

[[15 20  4]
 [20 25  8]]


In [40]:
#division of two arrays
import numpy as np
a=np.array([[3,2,1],[2,1,4]])
b=np.array([[5,10,4],[10,25,2]])
print(np.divide(a,b))

[[0.6  0.2  0.25]
 [0.2  0.04 2.  ]]
