<a href="https://colab.research.google.com/github/surekhavydyula4-cmd/Numpy./blob/main/Numpy_attributes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# dtype
import numpy as np
a=[[1,2,3],[4,5,6]]
ar=np.array(a)
print(ar)
print(ar.dtype)

[[1 2 3]
 [4 5 6]]
int64


In [ ]:
# ndim
import numpy as np
a=[[1,2,3],[4,5,6]]
ar=np.array(a)
print(ar)
print(ar.ndim)


[[1 2 3]
 [4 5 6]]
2


In [ ]:
# shape
import numpy as np
a=[[1,2,3],[4,5,6]]
ar=np.array(a)
print(ar)
print(ar.shape)
print(ar.shape[0])
print(ar.shape[1])

[[1 2 3]
 [4 5 6]]
(2, 3)
2
3


In [ ]:
# size
import numpy as np
a=[[1,2,3],[4,5,6]]
ar=np.array(a)
print(ar)
print(ar.size)

[[1 2 3]
 [4 5 6]]
6


In [ ]:
# T
import numpy as np
a=[[1,2,3],[4,5,6]]
ar=np.array(a)
print(ar)
print(ar.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
