<a href="https://colab.research.google.com/github/surekhavydyula4-cmd/Numpy./blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# array from list
import numpy as np
a=[1,2,3]
arr=np.array(a)
print(arr)

[1 2 3]


In [ ]:
# Multi dimensional array
import numpy as np
a=[[1,2,3],[4,5,6]]
arr=np.array(a)
print(a)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
# array of zeroes
import numpy as np
ar=np.zeros((3,2)) # by default it takes float data type
print(ar)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# array of zeroes and int data type
import numpy as np
ar=np.zeros((3,2),int) # covert into int data type
print(ar)

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
# array of ones
import numpy as np
ar=np.ones((2,3),int)
print(ar)

[[1 1 1]
 [1 1 1]]


In [ ]:
# sequence of numbers
import numpy as np
ar=np.arange(0,10,4)
print(ar)

[0 4 8]


In [ ]:
# evenly spaced numbers
import numpy as np
ar=np.linspace(0,10,4)
print(ar)

[ 0.          3.33333333  6.66666667 10.        ]


In [ ]:
# fill specific number
import numpy as np
ar=np.full((3,2),3)
print(ar)

[[3 3]
 [3 3]
 [3 3]]


In [ ]:
# Daigonal matrix
import numpy as np
ar=np.eye(3,2)
print(ar)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [ ]:
# random numbers array
import numpy as np
import random
a=np.random.randint(1,10,(2,3))
print(a)

[[5 5 4]
 [3 9 3]]


In [ ]:
#indexing from 1D array
import numpy as np
a=[1,2,3,4,5]
ar=np.array(a)
print(ar)
print(ar[0])
print(ar[3])
print(ar[-3]) # backward index


[1 2 3 4 5]
1
4
3


In [ ]:
# indexing from 2D array
import numpy as np
a=[[1,2,3],[4,5,6]]
ar=np.array(a)
print(ar[0])
print(ar[1])
print(ar[0,1])
print(ar[1,1])
print(ar[1,2])
print(ar[-1,0])  # backward index
print(ar[-2,-1])

[1 2 3]
[4 5 6]
2
5
6
4
3


In [ ]:
# fancy indexing
import numpy as np
a=[1,2,3]
ar=np.array(a)
print(ar(0,2))

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
# slicing from 1D array
import numpy as np
a=[1,2,3,4,5,6]
arr=np.array(a)
print(arr)
print(arr[0:3])
print(arr[1:])
print(arr[:])
print(arr[:2])
print(arr[-1:3:-2])
print(arr[-1:-4:-1])

[1 2 3 4 5 6]
[1 2 3]
[2 3 4 5 6]
[1 2 3 4 5 6]
[1 2]
[6]
[6 5 4]


In [ ]:
# slicing from 2D array
import numpy as np
a=[[1,2,3],[4,5,6]]
ar=np.array(a)
print(ar[:])
print(ar[0:1])
print(ar[0:2,:])
print(ar[1,:])
print(ar[1,0:2])

[[1 2 3]
 [4 5 6]]
[[1 2 3]]
[[1 2 3]
 [4 5 6]]
[4 5 6]
[4 5]
